### ISSUE TITLE
CSS Broken after migrating to Gatsbyv2

### ISSUE THREAD

**Issue by rishichawda** [Codebrahma/gatsby-ecommerce-pwa#114]
- On direct visit of a page, the css styles are not applied. ( There are no external styles in the project. Only styled components have been used. ). If any other page is visited through the web app, the styles get fixed / applied. 

- On direct visit of product items page ( and often on other pages too ), the page will get stuck in a loop where it keeps refreshing. This is caused due to some issues in page data caching. 

The link to PR and issues related to this issue of Gatsby@2 : 

- https://github.com/gatsbyjs/gatsby/pull/7355 ( This is the latest PR referencing this issue and was merged to master and hence included in the latest release of Gatsby@2 as of now, but doesn't seem to fix the issue. )

- https://github.com/gatsbyjs/gatsby/issues/7376 ( Similar issue already open in gatsby's repository )

**Comment by davidbailey00** [comment]
Did you see the last few comments in #7376? This should be fixed by installing `gatsby-plugin-styled-components` and adding it to your `gatsby-config.js`.

**Comment by rishichawda** [comment]
Yes. Checked now. I'll give it a try and let you know in a while.
