### ISSUE TITLE
Style fixes

### ISSUE THREAD

**Issue by prasanna1211** [Codebrahma/gatsby-ecommerce-pwa#18]
1. Underline on hover of nav items should be removed. Change it to some hover color with grey.
2. Reduce the product image size in sm and xs screens.
3. Change the product page styles a bit. Spacing seems to be improper.
4. Navbar design should be changed in mobile. Instead of category have a home icon on left and cart icon on right. Change the design similar to [this](https://www.w3schools.com/howto/howto_js_topnav_responsive.asp) in terms of content. Change the color to grey.

**Comment by prasanna1211** [comment]
5. Remove animation on the front end banner.

**Comment by KRRISH96** [comment]
Completed #21 #22 #24
