### ISSUE TITLE
Checkout Page Fixes

### ISSUE THREAD

**Issue by prasanna1211** [Codebrahma/gatsby-ecommerce-pwa#29]
1. Remove shipping method
2. Checkout page container is not wrapped in the correct width.
3. Payment section not responsive enough.
4. Scrolling should happen till payment with all sections opened.
5. If online warning message should appear by disabling the payment.

**Comment by KRRISH96** [comment]
6. Delete button in IPHONE responsiveness bug
7. Shop now button home page small screen
8. Add stripe.

**Comment by KRRISH96** [comment]
1,2,3,5,7---fixed
4,6,8 --pending

**Comment by KRRISH96** [comment]
fixed
