### ISSUE TITLE
Create product listing page

### ISSUE THREAD

**Issue by prasanna1211** [Codebrahma/gatsby-ecommerce-pwa#40]
- [x] UI should be similar to this https://getgrowfit.com/products/the-lean-machine-diet-7-day-subscription

- [x] Mock whatever data is needed.

- [x] build only till FAQs. Leave blog, related recipies

**Comment by prasanna1211** [comment]
The structure for the mock data can be bought from localhost:8000/___graphql. You can see any sample query in our app. You can see more using this. https://www.gatsbyjs.org/packages/gatsby-source-shopify/

**Comment by KRRISH96** [comment]
done
